version: 2
jobs:
  build:
    docker:
      - image: node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: coverage/junit/js-test-results.xml
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage
workflows:
  version: 2
  workflow:
    jobs:
      - build
